# Generated by Django 3.2 on 2022-04-10 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='deafault_forname',
            new_name='default_forname',
        ),
    ]
