# Generated by Django 3.2 on 2022-05-01 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20220501_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='default_mobile_number',
            new_name='default_phone_number',
        ),
    ]
