# Generated by Django 3.2 on 2022-05-06 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_rename_default_mobile_number_userprofile_default_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='default_forname',
            new_name='default_first_name',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='default_surname',
            new_name='default_last_name',
        ),
    ]
