""" This module contains the post review form for the review app """

from django import forms
from .models import Reviews


class PostReviewForm(forms.ModelForm):
    """
    The form to handle posting product reviews.
    """

    RATING = ((4, "5 Star"), (3, "4 Star"), (2, "3 Star"), (1, "2 Star"), (0, "1 Star"))  # noqa: E501

    rating = forms.ChoiceField(
        label='Rating',
        required=True,
        choices=RATING,
        widget=forms.Select,
    )

    review = forms.CharField(
        label='Review',
        required=True,
        widget=forms.Textarea(attrs={
            'placeholder': 'What did you think of the prodcut?'
        }),
        max_length=200,
    )

    class Meta:
        """
        Specifies the  Reviews model to inherit from and the fields to
        display, excludes all autogenerated fields.
        """
        model = Reviews
        fields = ('rating', 'review',)
