""" This module contains the post review form for the review app """

from django import forms
from .models import Reviews


class PostReviewForm(forms.ModelForm):
    """
    The form to handle posting product reviews.
    """

    rating = forms.IntegerField(
        label='Rating',
        required=True,
    )

    review = forms.CharField(
        label='Review',
        required=True,
        widget=forms.Textarea(attrs={
            'placeholder': 'What did you think of the prodcut?'
        }),
        max_length=200,
    )

    class Meta:
        """
        Specifies the  Reviews model to inherit from and the fields to
        display, excludes all autogenerated fields.
        """
        model = Reviews
        fields = ('rating', 'review',)

    def __init__(self, *args, **kwargs):
        """
        Over ride the default save method.

        Add the autofocus class to the 'rating' field.
        """
        super().__init__(*args, **kwargs)
        self.fields['rating'].widget.attrs['autofocus'] = True
