# Generated by Django 3.2 on 2022-05-12 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_rename_original_bag_order_original_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'processing'), (1, 'packaged'), (2, 'posted')], default=0),
        ),
    ]
