# Generated by Django 3.2 on 2022-04-12 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_weight_in_grams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='weight_in_grams',
        ),
        migrations.AddField(
            model_name='product',
            name='has_weights',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
