# Generated by Django 3.2 on 2022-04-13 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20220412_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='has_weights',
        ),
        migrations.AddField(
            model_name='product',
            name='weight_in_grams',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
