# Generated by Django 3.2 on 2022-04-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20220418_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='popular_in_00s',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='popular_in_80s',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='popular_in_90s',
            field=models.BooleanField(default=True),
        ),
    ]
