# Generated by Django 3.2 on 2022-04-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20220418_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='popular_in_00s',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='popular_in_80s',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='popular_in_90s',
            field=models.BooleanField(),
        ),
    ]
